# Single Source of Truth for Trading Configuration

# --- TIME SETTINGS ---
CUTOFF_TIME_STR = "15:20"  # EOD square-off time - trades allowed until this time
MARKET_CLOSE_TIME = "15:30"
MARKET_OPEN_TIME = "09:15"

# --- TRADING SCOPE ---
NIFTY50_SYMBOLS = [
    "RELIANCE", "TCS", "HDFCBANK", "BHARTIARTL", "ICICIBANK", "INFOSYS", "SBIN", "LICI", "ITC", "HINDUNILVR",
    "LT", "HCLTECH", "MARUTI", "SUNPHARMA", "TITAN", "ONGC", "TATAMOTORS", "NTPC", "AXISBANK", "NESTLEIND",
    "KOTAKBANK", "ULTRACEMCO", "ASIANPAINT", "BAJFINANCE", "WIPRO", "M&M", "TATACONSUM", "JSWSTEEL", "POWERGRID",
    "LTIM", "TECHM", "HINDALCO", "COALINDIA", "INDUSINDBK", "TATASTEEL", "CIPLA", "BAJAJFINSV", "GRASIM",
    "HDFCLIFE", "SBILIFE", "BPCL", "EICHERMOT", "HEROMOTOCO", "APOLLOHOSP", "ADANIENT", "BRITANNIA", "DIVISLAB",
    "DRREDDY", "TRENT", "ADANIPORTS"
]

SENSEX_SYMBOLS = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "BHARTIARTL", "INFOSYS", "SBIN", "LICI", "ITC", "HINDUNILVR",
    "LT", "MARUTI", "SUNPHARMA", "ONGC", "NTPC", "AXISBANK", "KOTAKBANK", "ULTRACEMCO", "ASIANPAINT", "NESTLEIND",
    "BAJFINANCE", "M&M", "POWERGRID", "TECHM", "TATAMOTORS", "TITAN", "INDUSINDBK", "HCLTECH", "WIPRO", "JSWSTEEL"
]

# --- STRATEGY SETTINGS ---
LIQUIDITY_TOP_N = 10
MIN_LIQUIDITY_CHANGE_PCT = 1.0
